CXXFLAGS = 
PARAM =
SOURCEDIR = source
BUILDIR = build
LIBS = -lSDL2 -lpthread -lavformat -lavcodec -lx264 -lavdevice -lavfilter -lavutil -lswscale -lpostproc -lm -I'/usr/local/include' -lswresample
EXECUTABLE= run

SOURCES = $(wildcard $(SOURCEDIR)/*.c)
DEPENDENCIES = $(wildcard $(SOURCEDIR)/*.h)

_OBJECTS = $(SOURCES:.c=.o)
OBJECTS = $(patsubst $(SOURCEDIR)/%,$(BUILDIR)/%,$(_OBJECTS))

$(BUILDIR)/%.o : $(SOURCEDIR)/%.c $(DEPENDENCIES)
	$(CXX) $(CXXFLAGS) -c $< -o $(LIBS) $@

$(EXECUTABLE) : $(OBJECTS)
	
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LIBS) \
	&& ./$(EXECUTABLE) $(PARAM)

.PHONY : cleanobj clean

cleanobj:
	rm $(OBJECTS)
clean:
	rm -rf ./build/*.o

